=== inspirehep/ng2-json-editor/example/assets/mock-data/experiments-schema.json
{
  "$schema": "http://json-schema.org/schema#", 
  "noAdditionalProperties": true, 
  "properties": {
    "accelerator": {
      "title": "Accelerator", 
      "type": "string"
    }, 
    "affiliations": {
      "items": {
        "noAdditionalProperties": true, 
        "properties": {
          "curated_relation": {
            "type": "boolean"
          }, 
          "name": {
            "title": "Name of the institution", 
            "type": "string"
          }, 
          "record": {
            "$schema": "http://json-schema.org/schema#", 
            "noAdditionalProperties": true, 
            "properties": {
              "$ref": {
                "description": "URL to the referenced resource", 
                "format": "url", 
                "type": "string"
              }
            }, 
            "required": [
              "$ref"
            ], 
            "type": "object"
          }
        }, 
        "type": "object"
      }, 
      "title": "Institutions with which experiment is affiliated.", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "collaboration": {
      "title": "Collaboration", 
      "type": "string"
    }, 
    "collaboration_alternative_names": {
      "items": {
        "title": "Collaboration alternative name", 
        "type": "string"
      }, 
      "title": "Collaboration alternative names", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "contact_details": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "description": "Contact person's data", 
        "noAdditionalProperties": true, 
        "properties": {
          "email": {
            "description": "Contact person's e-mail", 
            "format": "email", 
            "type": "string"
          }, 
          "name": {
            "description": "Contact person's name", 
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "curated_relation": {
      "title": "Curated relation", 
      "type": "boolean"
    }, 
    "date_approved": {
      "format": "date", 
      "title": "Date approved", 
      "type": "string"
    }, 
    "date_cancelled": {
      "format": "date", 
      "title": "Date cancelled", 
      "type": "string"
    }, 
    "date_completed": {
      "format": "date", 
      "title": "Date completed", 
      "type": "string"
    }, 
    "date_proposed": {
      "format": "date", 
      "title": "Date proposed", 
      "type": "string"
    }, 
    "date_started": {
      "format": "date", 
      "title": "Date started", 
      "type": "string"
    }, 
    "deleted": {
      "type": "boolean"
    }, 
    "description": {
      "items": {
        "type": "string"
      }, 
      "title": "Description", 
      "type": "array"
    }, 
    "experiment_names": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "source": {
            "type": "string"
          }, 
          "subtitle": {
            "type": "string"
          }, 
          "title": {
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "free_keywords": {
      "items": {
        "title": "Free keyword", 
        "type": "string"
      }, 
      "title": "Free keywords", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "hidden_note": {
      "title": "Hidden note", 
      "type": "string"
    }, 
    "inspire_categories": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "source": {
            "enum": [
              "curator", 
              "magpie", 
              "arxiv", 
              "user", 
              "undefined"
            ], 
            "type": "string"
          }, 
          "term": {
            "enum": [
              "Accelerators", 
              "Astrophysics", 
              "Computing", 
              "Data Analysis and Statistics", 
              "Experiment-HEP", 
              "Experiment-Nucl", 
              "General Physics", 
              "Gravitation and Cosmology", 
              "Instrumentation", 
              "Lattice", 
              "Math and Math Physics", 
              "Other", 
              "Phenomenology-HEP", 
              "Theory-HEP", 
              "Theory-Nucl"
            ], 
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "new_record": {
      "$schema": "http://json-schema.org/schema#", 
      "noAdditionalProperties": true, 
      "properties": {
        "$ref": {
          "description": "URL to the referenced resource", 
          "format": "url", 
          "type": "string"
        }
      }, 
      "required": [
        "$ref"
      ], 
      "type": "object"
    }, 
    "nonpublic_note": {
      "description": "FIXME: difference from hidden_note!?", 
      "title": "Non public note", 
      "type": "string"
    }, 
    "other_experiment_names": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "source": {
            "type": "string"
          }, 
          "subtitle": {
            "type": "string"
          }, 
          "title": {
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "public_note": {
      "title": "Public note", 
      "type": "string"
    }, 
    "related_experiments": {
      "items": {
        "noAdditionalProperties": true, 
        "properties": {
          "curated_relation": {
            "title": "Is the relation curated?", 
            "type": "boolean"
          }, 
          "name": {
            "title": "Name of related experiment", 
            "type": "string"
          }, 
          "record": {
            "$schema": "http://json-schema.org/schema#", 
            "noAdditionalProperties": true, 
            "properties": {
              "$ref": {
                "description": "URL to the referenced resource", 
                "format": "url", 
                "type": "string"
              }
            }, 
            "required": [
              "$ref"
            ], 
            "type": "object"
          }, 
          "relation": {
            "description": "FIXME: shall we simply store preceeding experiment and generate the symmetric relation automatically?", 
            "enum": [
              "predecessor", 
              "successor"
            ], 
            "title": "Type of relation", 
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "title": "Related experiments", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "self": {
      "$schema": "http://json-schema.org/schema#", 
      "noAdditionalProperties": true, 
      "properties": {
        "$ref": {
          "description": "URL to the referenced resource", 
          "format": "url", 
          "type": "string"
        }
      }, 
      "required": [
        "$ref"
      ], 
      "type": "object"
    }, 
    "spokespersons": {
      "items": {
        "noAdditionalProperties": true, 
        "properties": {
          "curated_relation": {
            "title": "Is the relation curated?", 
            "type": "boolean"
          }, 
          "current": {
            "title": "Is current Spokesperson?", 
            "type": "boolean"
          }, 
          "end_date": {
            "format": "date", 
            "title": "End date", 
            "type": "string"
          }, 
          "ids": {
            "items": {
              "$schema": "http://json-schema.org/schema#", 
              "anyOf": [
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "INSPIRE ID"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^INSPIRE-\\d{8}$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "INSPIRE BAI"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^(\\w+\\.)+\\d+$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "ORCID"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^\\d{4}-\\d{4}-\\d{4}-\\d{3}[0-9X]$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "JACOW"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^JACoW-\\d{8}$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "KAKEN"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^KAKEN-\\d{8}$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "ARXIV"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^\\w+_(\\w_)?\\d+$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "CERN"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^CERN-\\d+$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "DESY"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^DESY-\\d+$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "GOOGLESCHOLAR"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^(\\w|-){12}$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "VIAF"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^\\d{7,9}$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "RESEARCHERID"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^[A-z]-\\d{4}-\\d{4}$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "SCOPUS"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^\\d{10,11}$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "WIKIPEDIA"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^\\w+$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }, 
                {
                  "noAdditionalProperties": true, 
                  "properties": {
                    "type": {
                      "enum": [
                        "SLAC"
                      ], 
                      "type": "string"
                    }, 
                    "value": {
                      "pattern": "^SLAC-\\d+$", 
                      "type": "string"
                    }
                  }, 
                  "type": "object"
                }
              ], 
              "required": [
                "type", 
                "value"
              ]
            }, 
            "type": "array", 
            "uniqueItems": true
          }, 
          "name": {
            "title": "Name", 
            "type": "string"
          }, 
          "record": {
            "$schema": "http://json-schema.org/schema#", 
            "noAdditionalProperties": true, 
            "properties": {
              "$ref": {
                "description": "URL to the referenced resource", 
                "format": "url", 
                "type": "string"
              }
            }, 
            "required": [
              "$ref"
            ], 
            "type": "object"
          }, 
          "start_date": {
            "format": "date", 
            "title": "Start date", 
            "type": "string"
          }
        }, 
        "required": [
          "name"
        ], 
        "title": "Spokesperson", 
        "type": "object"
      }, 
      "title": "Spokespersons", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "titles": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "source": {
            "type": "string"
          }, 
          "subtitle": {
            "type": "string"
          }, 
          "title": {
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "urls": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "description": {
            "type": "string"
          }, 
          "value": {
            "format": "url", 
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }
  }, 
  "title": "Experiment", 
  "type": "object"
}

=== inspirehep/ng2-json-editor/example/assets/mock-data/experiments.json
{
  "accelerator": "mollit sed officia cil",
  "affiliations": [
    {
      "curated_relation": true,
      "name": "enim Excepteur eiusmod id",
      "record": {
        "$ref": "http://1"
      }
    },
    {
      "curated_relation": false,
      "name": "commodo",
      "record": {
        "$ref": "http://1YWt/;<SJi"
      }
    },
    {
      "curated_relation": false,
      "name": "minim Excepteur consequat ut",
      "record": {
        "$ref": "http://1D1R@ "
      }
    }
  ],
  "collaboration": "velit pariatur",
  "collaboration_alternative_names": [
    "sunt aute labore ea",
    "Lorem nulla eu qui magna",
    "eu in pariatur qui quis",
    "proident ipsum sit fugiat culpa",
    "ipsum "
  ],
  "contact_details": [
    {
      "email": "ABGSplUkIYKccz@uWFZKQZLUFaWJdHLADPPTeAlbhV.sgnh",
      "name": "laboris dolor tempor Ut sed"
    },
    {
      "email": "bVucEOBVajosS@MqlhBxHjo.jb",
      "name": "officia Lorem elit"
    },
    {
      "email": "Dhy1YFdgI4x3JEt@hjtPThIfGaBonS.ujxc",
      "name": "in Duis deserunt quis ex"
    },
    {
      "email": "P84JG@ZkKjywlBbwqXom.glx",
      "name": "Lorem magna"
    }
  ],
  "curated_relation": true,
  "date_approved": "dddd-dd-dd",
  "date_cancelled": "dddd-dd-dd",
  "date_completed": "dddd-dd-dd",
  "date_proposed": "dddd-dd-dd",
  "date_started": "dddd-dd-dd",
  "deleted": false,
  "description": [
    "laboris labore ea anim ut",
    "incididunt quis",
    "laborum est non",
    "enim e"
  ],
  "experiment_names": [
    {
      "source": "fugiat",
      "subtitle": "velit Duis ad",
      "title": "eiusmod in esse ullamco elit"
    }
  ],
  "free_keywords": [
    "enim labore",
    "et"
  ],
  "hidden_note": "est quis",
  "inspire_categories": [
    {
      "source": "curator",
      "term": "Experiment-Nucl"
    },
    {
      "source": "curator",
      "term": "Computing"
    }
  ],
  "new_record": {
    "$ref": "http://1*,K"
  },
  "nonpublic_note": "nulla ut",
  "other_experiment_names": [
    {
      "source": "ut",
      "subtitle": "laboris",
      "title": "eiusmod do labore consequat velit"
    },
    {
      "source": "deserunt exercitation consequat proident",
      "subtitle": "proident laborum exercitation",
      "title": "nostrud nulla"
    },
    {
      "source": "deserunt tempor consectetur Ut",
      "subtitle": "Excepteur commodo esse culpa",
      "title": "pariatur Excepteur dolore"
    }
  ],
  "public_note": "veniam officia aliqua aliquip nisi",
  "related_experiments": [
    {
      "curated_relation": false,
      "name": "mollit",
      "record": {
        "$ref": "http://1KnFy[+eEf"
      },
      "relation": "successor"
    },
    {
      "curated_relation": true,
      "name": "velit",
      "record": {
        "$ref": "http://1K4Q"
      },
      "relation": "predecessor"
    }
  ],
  "self": {
    "$ref": "http://1SZp@D3[!0"
  },
  "spokespersons": [
    {
      "curated_relation": true,
      "current": false,
      "end_date": "dddd-dd-dd",
      "ids": [
        {
          "type": "KAKEN",
          "value": "KAKEN-87182593"
        }
      ],
      "name": "laborum in ad",
      "record": {
        "$ref": "http://1<}+u2Tr"
      },
      "start_date": "dddd-dd-dd"
    },
    {
      "curated_relation": true,
      "current": true,
      "end_date": "dddd-dd-dd",
      "ids": [
        {
          "type": "KAKEN",
          "value": "KAKEN-76028386"
        }
      ],
      "name": "est dolore",
      "record": {
        "$ref": "http://1)qH[Xg:(X]"
      },
      "start_date": "dddd-dd-dd"
    },
    {
      "curated_relation": false,
      "current": false,
      "end_date": "dddd-dd-dd",
      "ids": [
        {
          "type": "KAKEN",
          "value": "KAKEN-23996332"
        },
        {
          "type": "KAKEN",
          "value": "KAKEN-01352928"
        },
        {
          "type": "KAKEN",
          "value": "KAKEN-23136290"
        },
        {
          "type": "KAKEN",
          "value": "KAKEN-57118831"
        }
      ],
      "name": "eiusmod do proident id",
      "record": {
        "$ref": "http://1V5a6"
      },
      "start_date": "dddd-dd-dd"
    },
    {
      "curated_relation": true,
      "current": true,
      "end_date": "dddd-dd-dd",
      "ids": [
        {
          "type": "KAKEN",
          "value": "KAKEN-81751386"
        },
        {
          "type": "KAKEN",
          "value": "KAKEN-12336793"
        },
        {
          "type": "KAKEN",
          "value": "KAKEN-73661888"
        }
      ],
      "name": "commodo anim culpa dolor",
      "record": {
        "$ref": "http://1/J="
      },
      "start_date": "dddd-dd-dd"
    }
  ],
  "titles": [
    {
      "source": "in fugiat ad enim consectetur",
      "subtitle": "aute nulla exercitation do dolor",
      "title": "cillum Lorem fugiat"
    },
    {
      "source": "commodo eiusmod consequat sunt",
      "subtitle": "sunt dolor",
      "title": "aliquip ex pariatur Lorem ea"
    },
    {
      "source": "minim",
      "subtitle": "exercitation eiusm",
      "title": "qui"
    },
    {
      "source": "irure",
      "subtitle": "nulla",
      "title": "laborum Ut Excepteur"
    }
  ],
  "urls": [
    {
      "description": "volupt",
      "value": "http://1|sYH1"
    },
    {
      "description": "commodo dolor incididunt id",
      "value": "http://1!h7H?9=k"
    },
    {
      "description": "ad nulla",
      "value": "http://1BKGlj?2\""
    }
  ]
}
