=== inspirehep/ng2-json-editor/example/assets/mock-data/institutions-schema.json
{
  "$schema": "http://json-schema.org/schema#", 
  "noAdditionalProperties": true, 
  "properties": {
    "ICN": {
      "description": "HEP affiliation following new standards", 
      "items": {
        "type": "string"
      }, 
      "title": "New INSPIRE control number", 
      "type": "array"
    }, 
    "address": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "description": "Address", 
        "noAdditionalProperties": true, 
        "properties": {
          "city": {
            "description": "City", 
            "type": "string"
          }, 
          "country_code": {
            "$schema": "http://json-schema.org/schema#", 
            "enum": [
              "AB", 
              "AF", 
              "AN", 
              "AX", 
              "AL", 
              "DZ", 
              "AS", 
              "AD", 
              "AO", 
              "AI", 
              "AQ", 
              "AG", 
              "AR", 
              "AM", 
              "AW", 
              "AU", 
              "AT", 
              "AZ", 
              "BS", 
              "BH", 
              "BD", 
              "BB", 
              "BY", 
              "BE", 
              "BZ", 
              "BJ", 
              "BM", 
              "BT", 
              "BO", 
              "BQ", 
              "BA", 
              "BW", 
              "BV", 
              "BR", 
              "IO", 
              "BN", 
              "BG", 
              "BF", 
              "BI", 
              "KH", 
              "CM", 
              "CA", 
              "CV", 
              "KY", 
              "CF", 
              "TD", 
              "CL", 
              "CN", 
              "CX", 
              "CC", 
              "CO", 
              "CS", 
              "KM", 
              "CG", 
              "CD", 
              "CK", 
              "CR", 
              "CI", 
              "HR", 
              "CU", 
              "CW", 
              "CY", 
              "CZ", 
              "DK", 
              "DJ", 
              "DM", 
              "DO", 
              "EC", 
              "EG", 
              "SV", 
              "GQ", 
              "ER", 
              "EE", 
              "ET", 
              "FK", 
              "FO", 
              "FJ", 
              "FI", 
              "FR", 
              "GF", 
              "PF", 
              "TF", 
              "GA", 
              "GM", 
              "GE", 
              "DE", 
              "GH", 
              "GI", 
              "GR", 
              "GL", 
              "GD", 
              "GP", 
              "GU", 
              "GT", 
              "GG", 
              "GN", 
              "GW", 
              "GY", 
              "HT", 
              "HM", 
              "VA", 
              "HN", 
              "HK", 
              "HU", 
              "IS", 
              "IN", 
              "ID", 
              "IR", 
              "IQ", 
              "IE", 
              "IM", 
              "IL", 
              "IT", 
              "JM", 
              "JP", 
              "JE", 
              "JO", 
              "KZ", 
              "KE", 
              "KI", 
              "KP", 
              "KR", 
              "KW", 
              "KG", 
              "LA", 
              "LV", 
              "LB", 
              "LS", 
              "LR", 
              "LY", 
              "LI", 
              "LT", 
              "LU", 
              "MO", 
              "MK", 
              "MG", 
              "MW", 
              "MY", 
              "MV", 
              "ML", 
              "MT", 
              "MH", 
              "MQ", 
              "MR", 
              "MU", 
              "YT", 
              "MX", 
              "FM", 
              "MD", 
              "MC", 
              "MN", 
              "ME", 
              "MS", 
              "MA", 
              "MZ", 
              "MM", 
              "NA", 
              "NR", 
              "NP", 
              "NL", 
              "NC", 
              "NT", 
              "NZ", 
              "NI", 
              "NE", 
              "NG", 
              "NU", 
              "NF", 
              "MP", 
              "NO", 
              "OM", 
              "PK", 
              "PW", 
              "PS", 
              "PA", 
              "PG", 
              "PY", 
              "PE", 
              "PH", 
              "PN", 
              "PL", 
              "PT", 
              "PR", 
              "QA", 
              "RE", 
              "RO", 
              "RU", 
              "RW", 
              "BL", 
              "SH", 
              "KN", 
              "LC", 
              "MF", 
              "PM", 
              "VC", 
              "WS", 
              "SM", 
              "ST", 
              "SA", 
              "SN", 
              "RS", 
              "SC", 
              "SL", 
              "SG", 
              "SX", 
              "SK", 
              "SI", 
              "SB", 
              "SO", 
              "ZA", 
              "GS", 
              "SS", 
              "ES", 
              "LK", 
              "SD", 
              "SR", 
              "SJ", 
              "SU", 
              "SZ", 
              "SE", 
              "CH", 
              "SY", 
              "TW", 
              "TJ", 
              "TZ", 
              "TH", 
              "TL", 
              "TG", 
              "TK", 
              "TO", 
              "TT", 
              "TN", 
              "TR", 
              "TM", 
              "TC", 
              "TV", 
              "UG", 
              "UA", 
              "AE", 
              "GB", 
              "US", 
              "UM", 
              "UY", 
              "UZ", 
              "VU", 
              "VE", 
              "VN", 
              "VG", 
              "VI", 
              "WF", 
              "EH", 
              "YE", 
              "YU", 
              "ZM", 
              "ZW"
            ], 
            "maxLength": 2, 
            "minLength": 2, 
            "title": "Country code according to ISO 3166-1-alpha-2 with few additions (CS - Czechoslovakia, YU - Yugoslavia, AB - Serbia and Montenegro, AN - Netherlands Antilles, NT - Neutral Zone)", 
            "type": "string"
          }, 
          "latitude": {
            "description": "Latitude of the place", 
            "type": "integer"
          }, 
          "longitude": {
            "description": "Longitude of the place", 
            "type": "integer"
          },
          "original address": {
            "description": "Original address, entities separeted with a comma", 
            "type": "string"
          }, 
          "postal_code": {
            "description": "Postal code", 
            "type": "string"
          }, 
          "state": {
            "description": "State or province", 
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "core": {
      "description": "Is this a CORE institution?", 
      "title": "CORE", 
      "type": "boolean"
    }, 
    "deleted": {
      "type": "boolean"
    }, 
    "department": {
      "description": "Subordinate unit in native language", 
      "items": {
        "type": "string"
      }, 
      "title": "Department", 
      "type": "array"
    }, 
    "department_acronym": {
      "description": "Subordinate unit well-known acronym", 
      "title": "Department acronym", 
      "type": "string"
    }, 
    "extra_words": {
      "items": {
        "type": "string"
      }, 
      "title": "Extra words", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "field_activity": {
      "items": {
        "enum": [
          "University", 
          "Research Center", 
          "Company", 
          "Other"
        ], 
        "type": "string"
      }, 
      "title": "Field of activity", 
      "type": "array"
    }, 
    "hidden_notes": {
      "items": {
        "title": "Hidden note", 
        "type": "string"
      }, 
      "title": "Hidden notes", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "historical_data": {
      "items": {
        "type": "string"
      }, 
      "type": "array"
    }, 
    "ids": {
      "items": {
        "anyOf": [
          {
            "noAdditionalProperties": true, 
            "properties": {
              "type": {
                "enum": [
                  "HAL"
                ], 
                "type": "string"
              }, 
              "value": {
                "pattern": "^\\d+$", 
                "type": "string"
              }
            }, 
            "type": "object"
          }
        ], 
        "required": [
          "type", 
          "value"
        ]
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "inspire_categories": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "source": {
            "enum": [
              "curator", 
              "magpie", 
              "arxiv", 
              "user", 
              "undefined"
            ], 
            "type": "string"
          }, 
          "term": {
            "enum": [
              "Accelerators", 
              "Astrophysics", 
              "Computing", 
              "Data Analysis and Statistics", 
              "Experiment-HEP", 
              "Experiment-Nucl", 
              "General Physics", 
              "Gravitation and Cosmology", 
              "Instrumentation", 
              "Lattice", 
              "Math and Math Physics", 
              "Other", 
              "Phenomenology-HEP", 
              "Theory-HEP", 
              "Theory-Nucl"
            ], 
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "institution": {
      "description": "Corporate name in native language", 
      "items": {
        "type": "string"
      }, 
      "title": "Institution name", 
      "type": "array"
    }, 
    "institution_acronym": {
      "description": "Corporate well-known acronym", 
      "title": "Institution acronym", 
      "type": "string"
    }, 
    "location": {
      "noAdditionalProperties": true, 
      "properties": {
        "latitude": {
          "description": "FIXME: we can populate this programmatically with Google APIs", 
          "title": "latitude", 
          "type": "integer"
        }, 
        "longitude": {
          "description": "FIXME: we can populate this programmatically with Google APIs", 
          "title": "longitude", 
          "type": "integer"
        }
      }, 
      "title": "GPS location", 
      "type": "object"
    }, 
    "name_variants": {
      "items": {
        "noAdditionalProperties": true, 
        "properties": {
          "source": {
            "description": "FIXME: Do we really care about the source?", 
            "enum": [
              "DESY", 
              "DESY_AFF", 
              "ADS", 
              "INSPIRE"
            ], 
            "title": "Name variant source", 
            "type": "string"
          }, 
          "value": {
            "items": {
              "type": "string"
            }, 
            "type": "array", 
            "uniqueItems": true
          }
        }, 
        "title": "Name variant", 
        "type": "object"
      }, 
      "title": "Name variants", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "new_record": {
      "$schema": "http://json-schema.org/schema#", 
      "noAdditionalProperties": true, 
      "properties": {
        "$ref": {
          "description": "URL to the referenced resource", 
          "format": "url", 
          "type": "string"
        }
      }, 
      "required": [
        "$ref"
      ], 
      "type": "object"
    }, 
    "non_public_notes": {
      "items": {
        "title": "Non-Public note", 
        "type": "string"
      }, 
      "title": "FIXME: Difference between hidden note?", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "public_notes": {
      "items": {
        "title": "Public note", 
        "type": "string"
      }, 
      "title": "Public notes", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "related_institutes": {
      "items": {
        "noAdditionalProperties": true, 
        "properties": {
          "curated_relation": {
            "title": "Is the relation curated?", 
            "type": "boolean"
          }, 
          "name": {
            "title": "Name of related institute", 
            "type": "string"
          }, 
          "record": {
            "$schema": "http://json-schema.org/schema#", 
            "noAdditionalProperties": true, 
            "properties": {
              "$ref": {
                "description": "URL to the referenced resource", 
                "format": "url", 
                "type": "string"
              }
            }, 
            "required": [
              "$ref"
            ], 
            "type": "object"
          }, 
          "relation_type": {
            "enum": [
              "predecessor", 
              "successor", 
              "parent", 
              "superseded", 
              "other"
            ], 
            "title": "Relation type", 
            "type": "string"
          }
        }, 
        "title": "Related institute", 
        "type": "object"
      }, 
      "title": "Related institutes", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "self": {
      "$schema": "http://json-schema.org/schema#", 
      "noAdditionalProperties": true, 
      "properties": {
        "$ref": {
          "description": "URL to the referenced resource", 
          "format": "url", 
          "type": "string"
        }
      }, 
      "required": [
        "$ref"
      ], 
      "type": "object"
    }, 
    "time_zone": {
      "description": "FIXME: we can populate this programmatically with Google APIs", 
      "enum": [
        "there", 
        "must", 
        "be", 
        "one"
      ], 
      "title": "Time zone", 
      "type": "string"
    }, 
    "urls": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "description": {
            "type": "string"
          }, 
          "value": {
            "format": "url", 
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }
  }, 
  "title": "Institution", 
  "type": "object"
}

=== inspirehep/ng2-json-editor/example/assets/mock-data/institutions.json
{
  "ICN": [
    "Excepteur veniam dolore ea",
    "deserunt aliqua incididunt aliq",
    "anim",
    "dolore"
  ],
  "address": [
    {
      "city": "deserunt",
      "country_code": "GB",
      "latitude": -39663177,
      "longitude": -22281658,
      "original address": "laborum cupidatat eu nisi est",
      "postal_code": "exercitation commodo adipisicing reprehenderit dolore",
      "state": "ipsum consequat dolor enim ex"
    },
    {
      "city": "amet irure ullamco eu culpa",
      "country_code": "NT",
      "latitude": 82361131,
      "longitude": 87368296,
      "original address": "eu et dolore in",
      "postal_code": "reprehenderit occaecat pariatur",
      "state": "mollit do Ut in incididunt"
    },
    {
      "city": "incididunt cillum tempor",
      "country_code": "PG",
      "latitude": -25596441,
      "longitude": -19424458,
      "original address": "quis",
      "postal_code": "in",
      "state": "labore in anim"
    },
    {
      "city": "i",
      "country_code": "LI",
      "latitude": 60759164,
      "longitude": -27431765,
      "original address": "commodo laborum",
      "postal_code": "aliquip minim Lorem ut dolor",
      "state": "tempor anim Excepteur mollit aute"
    },
    {
      "city": "aliqua Ut sed",
      "country_code": "CR",
      "latitude": -92616445,
      "longitude": 38587160,
      "original address": "velit eiusmod",
      "postal_code": "non in Excepteur ut ad",
      "state": "et consectetur deserunt ipsum"
    }
  ],
  "core": true,
  "deleted": false,
  "department": [
    "dolore",
    "enim",
    "id laboris enim adipisicing",
    "consectetur reprehenderit"
  ],
  "department_acronym": "adipisicing",
  "extra_words": [
    "Lorem labore nostrud",
    "consequat Excepteur",
    "eu"
  ],
  "field_activity": [
    "Company",
    "University"
  ],
  "hidden_notes": [
    "proident irure sed",
    "amet tempor"
  ],
  "historical_data": [
    "officia sint",
    "ipsum"
  ],
  "ids": [
    {
      "type": "HAL",
      "value": "3"
    },
    {
      "type": "HAL",
      "value": "02043107025"
    }
  ],
  "inspire_categories": [
    {
      "source": "user",
      "term": "Theory-Nucl"
    },
    {
      "source": "undefined",
      "term": "Computing"
    },
    {
      "source": "curator",
      "term": "Computing"
    },
    {
      "source": "user",
      "term": "Theory-HEP"
    },
    {
      "source": "arxiv",
      "term": "Astrophysics"
    }
  ],
  "institution": [
    "exercitation commodo eu ex",
    "enim in sint",
    "dolore",
    "in enim"
  ],
  "institution_acronym": "velit ullamco incididunt mol",
  "location": {
    "latitude": -34224204,
    "longitude": -84039479
  },
  "name_variants": [
    {
      "source": "INSPIRE",
      "value": [
        "amet mollit",
        "eiusmod et Lorem Duis Ut",
        "reprehenderit aliqua nostrud adipisicing",
        "mollit adipisicing",
        "aliquip Duis sunt"
      ]
    },
    {
      "source": "DESY_AFF",
      "value": [
        "Ut officia ut",
        "",
        "ut"
      ]
    },
    {
      "source": "DESY_AFF",
      "value": [
        "labore dolore sunt ullamco id",
        "cupidatat Lorem ad",
        "irure",
        "adipisicing Lorem esse aute"
      ]
    },
    {
      "source": "ADS",
      "value": [
        "cupidatat",
        "id ex exercitation",
        "ipsum in Lorem sint",
        "deserunt"
      ]
    }
  ],
  "new_record": {
    "$ref": "http://1E=0?2"
  },
  "non_public_notes": [
    "culpa"
  ],
  "public_notes": [
    "reprehenderit eiusmod ea",
    "id laboris"
  ],
  "related_institutes": [
    {
      "curated_relation": false,
      "name": "proident elit dolor",
      "record": {
        "$ref": "http://1["
      },
      "relation_type": "superseded"
    },
    {
      "curated_relation": true,
      "name": "et nostrud",
      "record": {
        "$ref": "http://1FY)ZA"
      },
      "relation_type": "predecessor"
    }
  ],
  "self": {
    "$ref": "http://17"
  },
  "time_zone": "one",
  "urls": [
    {
      "description": "",
      "value": "http://1)4"
    }
  ]
}
