=== inspirehep/ng2-json-editor/example/assets/mock-data/journals-schema.json
{
  "$schema": "http://json-schema.org/schema#", 
  "noAdditionalProperties": true, 
  "properties": {
    "coden": {
      "items": {
        "pattern": "^[0-9\\.A-Z_-]{4,6}$", 
        "title": "CODEN", 
        "type": "string"
      }, 
      "title": "CODEN", 
      "type": "array", 
      "uniqueItems": true
    }, 
    "deleted": {
      "type": "boolean"
    }, 
    "history": {
      "title": "History", 
      "type": "string"
    }, 
    "issn": {
      "items": {
        "noAdditionalProperties": true, 
        "properties": {
          "comment": {
            "description": "Further information about type.", 
            "type": "string"
          }, 
          "medium": {
            "description": "Medium (type) of the ISSN.", 
            "enum": [
              "online", 
              "print"
            ], 
            "type": "string"
          }, 
          "value": {
            "pattern": "^\\d{4}-\\d{3}[\\dX]$", 
            "type": "string"
          }
        }, 
        "required": [
          "value"
        ], 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "journal_handling": {
      "title": "Journal handling", 
      "type": "string"
    }, 
    "journal_titles": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "source": {
            "type": "string"
          }, 
          "subtitle": {
            "type": "string"
          }, 
          "title": {
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "license": {
      "enum": [
        "probably", 
        "it", 
        "is", 
        "needed"
      ], 
      "title": "License", 
      "type": "string"
    }, 
    "license_urls": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "description": {
            "type": "string"
          }, 
          "value": {
            "format": "url", 
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "new_record": {
      "$schema": "http://json-schema.org/schema#", 
      "noAdditionalProperties": true, 
      "properties": {
        "$ref": {
          "description": "URL to the referenced resource", 
          "format": "url", 
          "type": "string"
        }
      }, 
      "required": [
        "$ref"
      ], 
      "type": "object"
    }, 
    "nonpublic_note": {
      "title": "Non public note", 
      "type": "string"
    }, 
    "peer_reviewed": {
      "title": "Is the journal peer-reviewed?", 
      "type": "boolean"
    }, 
    "public_note": {
      "title": "Publisher", 
      "type": "string"
    }, 
    "publisher": {
      "items": {
        "type": "string"
      }, 
      "title": "Publisher", 
      "type": "array"
    }, 
    "relation": {
      "noAdditionalProperties": true, 
      "properties": {
        "curated_relation": {
          "title": "Is the relation curated?", 
          "type": "boolean"
        }, 
        "issn": {
          "pattern": "^\\d{4}-\\d{3}[\\dX]$", 
          "title": "ISSN of the related record", 
          "type": "string"
        }, 
        "record": {
          "$schema": "http://json-schema.org/schema#", 
          "noAdditionalProperties": true, 
          "properties": {
            "$ref": {
              "description": "URL to the referenced resource", 
              "format": "url", 
              "type": "string"
            }
          }, 
          "required": [
            "$ref"
          ], 
          "type": "object"
        }, 
        "relation": {
          "description": "FIXME: as usual, shall we capture only superseeded records and derive the symmetric relation automatically?", 
          "enum": [
            "superseded record", 
            "superseeding record"
          ], 
          "title": "Type of relation", 
          "type": "string"
        }
      }, 
      "required": [
        "relation", 
        "issn"
      ], 
      "title": "Relation", 
      "type": "object"
    }, 
    "self": {
      "$schema": "http://json-schema.org/schema#", 
      "noAdditionalProperties": true, 
      "properties": {
        "$ref": {
          "description": "URL to the referenced resource", 
          "format": "url", 
          "type": "string"
        }
      }, 
      "required": [
        "$ref"
      ], 
      "type": "object"
    }, 
    "short_titles": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "source": {
            "type": "string"
          }, 
          "subtitle": {
            "type": "string"
          }, 
          "title": {
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "title_variants": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "source": {
            "type": "string"
          }, 
          "subtitle": {
            "type": "string"
          }, 
          "title": {
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }, 
    "urls": {
      "items": {
        "$schema": "http://json-schema.org/schema#", 
        "noAdditionalProperties": true, 
        "properties": {
          "description": {
            "type": "string"
          }, 
          "value": {
            "format": "url", 
            "type": "string"
          }
        }, 
        "type": "object"
      }, 
      "type": "array", 
      "uniqueItems": true
    }
  }, 
  "title": "Journal", 
  "type": "object"
}

=== inspirehep/ng2-json-editor/example/assets/mock-data/journals.json
{
  "coden": [
    "XULTN",
    "KTN._W",
    "8LHX"
  ],
  "deleted": true,
  "history": "dolor commodo minim",
  "issn": [
    {
      "comment": "esse id in sit",
      "medium": "online",
      "value": "3144-7818"
    },
    {
      "comment": "nisi enim id",
      "medium": "print",
      "value": "3937-956X"
    }
  ],
  "journal_handling": "laboris irure sit esse",
  "journal_titles": [
    {
      "source": "Excepteur cupidat",
      "subtitle": "sit",
      "title": "officia nostrud"
    },
    {
      "source": "sunt aliqua a",
      "subtitle": "nulla",
      "title": "nulla"
    },
    {
      "source": "adipisicing elit in sit",
      "subtitle": "amet mollit occaecat laboris eu",
      "title": "ex laborum nulla enim"
    }
  ],
  "license": "is",
  "license_urls": [
    {
      "description": "do in",
      "value": "http://18[U.2Y"
    },
    {
      "description": "sunt",
      "value": "http://1/[~e\""
    },
    {
      "description": "nisi et aliquip",
      "value": "http://1"
    },
    {
      "description": "ad irure",
      "value": "http://1"
    }
  ],
  "new_record": {
    "$ref": "http://1:"
  },
  "nonpublic_note": "eu dolore in",
  "peer_reviewed": true,
  "public_note": "qui ea minim dolor sunt",
  "publisher": [
    "aliqua aliquip",
    "sint cillum esse"
  ],
  "relation": {
    "curated_relation": false,
    "issn": "1654-2565",
    "record": {
      "$ref": "http://1brHXU"
    },
    "relation": "superseded record"
  },
  "self": {
    "$ref": "http://1>#!0n3Qa"
  },
  "short_titles": [
    {
      "source": "proident",
      "subtitle": "veniam",
      "title": "exercitation"
    }
  ],
  "title_variants": [
    {
      "source": "consequat",
      "subtitle": "Ut sed veniam consectetur dolore",
      "title": "Lorem esse ullamco reprehenderit"
    },
    {
      "source": "ea officia",
      "subtitle": "pariatur velit tempor elit",
      "title": "veniam do consectetur elit reprehenderit"
    }
  ],
  "urls": [
    {
      "description": "adipisicing",
      "value": "http://1gwtVj@i]"
    },
    {
      "description": "dolor",
      "value": "http://1f"
    },
    {
      "description": "do",
      "value": "http://1}-nXXGzZe"
    },
    {
      "description": "commodo minim dolore",
      "value": "http://1"
    },
    {
      "description": "sit do eu",
      "value": "http://1q"
    }
  ]
}
